# --- !Ups

create table "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "surname" varchar not null,
  "role" varchar not null,
  "age" int not null
);

create table "goals" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "description" varchar not null,
  "score" int not null
);

# --- !Downs

drop table "people" if exists;
drop table "goals" if exists;
